#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("visvitalis.Resource", IsApplication=true)]

namespace visvitalis
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int customTypeface = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f05000d
			public const int background = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int colorAccent = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int colorPrimary = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int colorPrimaryDark = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int common_action_bar_splitter = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int common_signin_btn_dark_text_default = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_signin_btn_dark_text_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_signin_btn_dark_text_focused = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_signin_btn_dark_text_pressed = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int common_signin_btn_default_background = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int common_signin_btn_light_text_default = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int common_signin_btn_light_text_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_signin_btn_light_text_focused = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int common_signin_btn_light_text_pressed = 2131034117;
			
			// aapt resource value: 0x7f050012
			public const int common_signin_btn_text_dark = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int common_signin_btn_text_light = 2131034131;
			
			// aapt resource value: 0x7f050011
			public const int divider = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int icons = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int primary_text = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int secondary_text = 2131034127;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ab_background_textured_maintheme = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ab_bottom_solid_maintheme = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_solid_maintheme = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_stacked_solid_maintheme = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ab_texture_tile_maintheme = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ab_transparent_maintheme = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_cab_done_default_maintheme = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_cab_done_focused_maintheme = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_cab_done_maintheme = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_cab_done_pressed_maintheme = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cab_background_bottom_maintheme = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cab_background_top_maintheme = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_full_open_on_phone = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_ic_googleplayservices = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_icon_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_icon_disabled_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_icon_disabled_focus_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_icon_disabled_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_icon_focus_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_icon_focus_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_icon_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_icon_normal_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_icon_normal_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_icon_pressed_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_icon_pressed_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_text_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_text_disabled_dark = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_signin_btn_text_disabled_focus_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_signin_btn_text_disabled_focus_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_signin_btn_text_disabled_light = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_signin_btn_text_focus_dark = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_signin_btn_text_focus_light = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_signin_btn_text_light = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_signin_btn_text_normal_dark = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_signin_btn_text_normal_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_signin_btn_text_pressed_dark = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_signin_btn_text_pressed_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int envelope54 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_launcher = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_plusone_medium_off_client = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_plusone_small_off_client = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_plusone_standard_off_client = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_plusone_tall_off_client = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Icon = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int in_message_bg = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int list_focused_maintheme = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int list_pressed_maintheme = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int menu_dropdown_panel_maintheme = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int out_message_bg = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int paperplane = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int progress_bg_maintheme = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int progress_horizontal_maintheme = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int progress_primary_maintheme = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int progress_secondary_maintheme = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int rounded_button = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int rounded_corners = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int selectable_background_maintheme = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int spinner_ab_default_maintheme = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int spinner_ab_disabled_maintheme = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int spinner_ab_focused_maintheme = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int spinner_ab_pressed_maintheme = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int spinner_background_ab_maintheme = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int SplashScreen = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int tab_indicator_ab_maintheme = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int tab_selected_focused_maintheme = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int tab_selected_maintheme = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int tab_selected_pressed_maintheme = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int tab_unselected_focused_maintheme = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int tab_unselected_maintheme = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int tab_unselected_pressed_maintheme = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int thememain_activated_background_holo_light = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int thememain_btn_check_holo_light = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int thememain_btn_check_off_disabled_focused_holo_light = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int thememain_btn_check_off_disabled_holo_light = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int thememain_btn_check_off_focused_holo_light = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int thememain_btn_check_off_holo_light = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int thememain_btn_check_off_pressed_holo_light = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int thememain_btn_check_on_disabled_focused_holo_light = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int thememain_btn_check_on_disabled_holo_light = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int thememain_btn_check_on_focused_holo_light = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int thememain_btn_check_on_holo_light = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int thememain_btn_check_on_pressed_holo_light = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int thememain_btn_default_disabled_focused_holo_light = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int thememain_btn_default_disabled_holo_light = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int thememain_btn_default_focused_holo_light = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int thememain_btn_default_holo_light = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int thememain_btn_default_normal_holo_light = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int thememain_btn_default_pressed_holo_light = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int thememain_btn_radio_holo_light = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int thememain_btn_radio_off_disabled_focused_holo_light = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int thememain_btn_radio_off_disabled_holo_light = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int thememain_btn_radio_off_focused_holo_light = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int thememain_btn_radio_off_holo_light = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int thememain_btn_radio_off_pressed_holo_light = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int thememain_btn_radio_on_disabled_focused_holo_light = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int thememain_btn_radio_on_disabled_holo_light = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int thememain_btn_radio_on_focused_holo_light = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int thememain_btn_radio_on_holo_light = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int thememain_btn_radio_on_pressed_holo_light = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int thememain_btn_rating_star_off_focused_holo_light = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int thememain_btn_rating_star_off_normal_holo_light = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int thememain_btn_rating_star_off_pressed_holo_light = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int thememain_btn_rating_star_on_focused_holo_light = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int thememain_btn_rating_star_on_normal_holo_light = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int thememain_btn_rating_star_on_pressed_holo_light = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int thememain_btn_toggle_holo_light = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int thememain_btn_toggle_off_disabled_focused_holo_light = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int thememain_btn_toggle_off_disabled_holo_light = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int thememain_btn_toggle_off_focused_holo_light = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int thememain_btn_toggle_off_normal_holo_light = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int thememain_btn_toggle_off_pressed_holo_light = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int thememain_btn_toggle_on_disabled_focused_holo_light = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int thememain_btn_toggle_on_disabled_holo_light = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int thememain_btn_toggle_on_focused_holo_light = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int thememain_btn_toggle_on_normal_holo_light = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int thememain_btn_toggle_on_pressed_holo_light = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int thememain_edit_text_holo_light = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int thememain_fastscroll_thumb_default_holo = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int thememain_fastscroll_thumb_holo = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int thememain_fastscroll_thumb_pressed_holo = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int thememain_ic_navigation_drawer = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int thememain_item_background_holo_light = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int thememain_list_activated_holo = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int thememain_list_focused_holo = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int thememain_list_longpressed_holo = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int thememain_list_pressed_holo_light = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int thememain_list_selector_background_transition_holo_light = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int thememain_list_selector_disabled_holo_light = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int thememain_list_selector_holo_light = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int thememain_progress_bg_holo_light = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int thememain_progress_horizontal_holo_light = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int thememain_progress_indeterminate_horizontal_holo_light = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int thememain_progress_primary_holo_light = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int thememain_progress_secondary_holo_light = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int thememain_progressbar_indeterminate_holo1 = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int thememain_progressbar_indeterminate_holo2 = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int thememain_progressbar_indeterminate_holo3 = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int thememain_progressbar_indeterminate_holo4 = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int thememain_progressbar_indeterminate_holo5 = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int thememain_progressbar_indeterminate_holo6 = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int thememain_progressbar_indeterminate_holo7 = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int thememain_progressbar_indeterminate_holo8 = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int thememain_rate_star_big_half_holo_light = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int thememain_rate_star_big_off_holo_light = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int thememain_rate_star_big_on_holo_light = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int thememain_rate_star_small_half_holo_light = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int thememain_rate_star_small_off_holo_light = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int thememain_rate_star_small_on_holo_light = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int thememain_ratingbar_full_empty_holo_light = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int thememain_ratingbar_full_filled_holo_light = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int thememain_ratingbar_full_holo_light = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int thememain_ratingbar_holo_light = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int thememain_ratingbar_small_holo_light = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int thememain_scrubber_control_disabled_holo = 2130837658;
			
			// aapt resource value: 0x7f02009b
			public const int thememain_scrubber_control_focused_holo = 2130837659;
			
			// aapt resource value: 0x7f02009c
			public const int thememain_scrubber_control_normal_holo = 2130837660;
			
			// aapt resource value: 0x7f02009d
			public const int thememain_scrubber_control_pressed_holo = 2130837661;
			
			// aapt resource value: 0x7f02009e
			public const int thememain_scrubber_control_selector_holo_light = 2130837662;
			
			// aapt resource value: 0x7f02009f
			public const int thememain_scrubber_primary_holo = 2130837663;
			
			// aapt resource value: 0x7f0200a0
			public const int thememain_scrubber_progress_horizontal_holo_light = 2130837664;
			
			// aapt resource value: 0x7f0200a1
			public const int thememain_scrubber_secondary_holo = 2130837665;
			
			// aapt resource value: 0x7f0200a2
			public const int thememain_scrubber_track_holo_light = 2130837666;
			
			// aapt resource value: 0x7f0200a3
			public const int thememain_spinner_background_holo_light = 2130837667;
			
			// aapt resource value: 0x7f0200a4
			public const int thememain_spinner_default_holo_light = 2130837668;
			
			// aapt resource value: 0x7f0200a5
			public const int thememain_spinner_disabled_holo_light = 2130837669;
			
			// aapt resource value: 0x7f0200a6
			public const int thememain_spinner_focused_holo_light = 2130837670;
			
			// aapt resource value: 0x7f0200a7
			public const int thememain_spinner_pressed_holo_light = 2130837671;
			
			// aapt resource value: 0x7f0200a8
			public const int thememain_switch_bg_disabled_holo_light = 2130837672;
			
			// aapt resource value: 0x7f0200a9
			public const int thememain_switch_bg_focused_holo_light = 2130837673;
			
			// aapt resource value: 0x7f0200aa
			public const int thememain_switch_bg_holo_light = 2130837674;
			
			// aapt resource value: 0x7f0200ab
			public const int thememain_switch_inner_holo_light = 2130837675;
			
			// aapt resource value: 0x7f0200ac
			public const int thememain_switch_thumb_activated_holo_light = 2130837676;
			
			// aapt resource value: 0x7f0200ad
			public const int thememain_switch_thumb_disabled_holo_light = 2130837677;
			
			// aapt resource value: 0x7f0200ae
			public const int thememain_switch_thumb_holo_light = 2130837678;
			
			// aapt resource value: 0x7f0200af
			public const int thememain_switch_thumb_pressed_holo_light = 2130837679;
			
			// aapt resource value: 0x7f0200b0
			public const int thememain_switch_track_holo_light = 2130837680;
			
			// aapt resource value: 0x7f0200b1
			public const int thememain_tab_indicator_holo = 2130837681;
			
			// aapt resource value: 0x7f0200b2
			public const int thememain_tab_selected_focused_holo = 2130837682;
			
			// aapt resource value: 0x7f0200b3
			public const int thememain_tab_selected_holo = 2130837683;
			
			// aapt resource value: 0x7f0200b4
			public const int thememain_tab_selected_pressed_holo = 2130837684;
			
			// aapt resource value: 0x7f0200b5
			public const int thememain_tab_unselected_focused_holo = 2130837685;
			
			// aapt resource value: 0x7f0200b6
			public const int thememain_tab_unselected_holo = 2130837686;
			
			// aapt resource value: 0x7f0200b7
			public const int thememain_tab_unselected_pressed_holo = 2130837687;
			
			// aapt resource value: 0x7f0200b8
			public const int thememain_text_select_handle_left = 2130837688;
			
			// aapt resource value: 0x7f0200b9
			public const int thememain_text_select_handle_middle = 2130837689;
			
			// aapt resource value: 0x7f0200ba
			public const int thememain_text_select_handle_right = 2130837690;
			
			// aapt resource value: 0x7f0200bb
			public const int thememain_textfield_activated_holo_light = 2130837691;
			
			// aapt resource value: 0x7f0200bc
			public const int thememain_textfield_default_holo_light = 2130837692;
			
			// aapt resource value: 0x7f0200bd
			public const int thememain_textfield_disabled_focused_holo_light = 2130837693;
			
			// aapt resource value: 0x7f0200be
			public const int thememain_textfield_disabled_holo_light = 2130837694;
			
			// aapt resource value: 0x7f0200bf
			public const int thememain_textfield_focused_holo_light = 2130837695;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public const int adjust_height = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int adjust_width = 2131296257;
			
			// aapt resource value: 0x7f090012
			public const int alertDescription = 2131296274;
			
			// aapt resource value: 0x7f090011
			public const int alertTitle = 2131296273;
			
			// aapt resource value: 0x7f09000e
			public const int button1 = 2131296270;
			
			// aapt resource value: 0x7f090016
			public const int button2 = 2131296278;
			
			// aapt resource value: 0x7f090015
			public const int button3 = 2131296277;
			
			// aapt resource value: 0x7f09000a
			public const int chatSendButton = 2131296266;
			
			// aapt resource value: 0x7f090007
			public const int container = 2131296263;
			
			// aapt resource value: 0x7f090003
			public const int content = 2131296259;
			
			// aapt resource value: 0x7f090005
			public const int contentWithBackground = 2131296261;
			
			// aapt resource value: 0x7f09000c
			public const int editText1 = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int editText2 = 2131296269;
			
			// aapt resource value: 0x7f090020
			public const int finish = 2131296288;
			
			// aapt resource value: 0x7f090010
			public const int fragmentContainer = 2131296272;
			
			// aapt resource value: 0x7f09000f
			public const int imageView1 = 2131296271;
			
			// aapt resource value: 0x7f090014
			public const int kmEditText = 2131296276;
			
			// aapt resource value: 0x7f09001a
			public const int line_a = 2131296282;
			
			// aapt resource value: 0x7f09001b
			public const int line_b = 2131296283;
			
			// aapt resource value: 0x7f09001c
			public const int line_c = 2131296284;
			
			// aapt resource value: 0x7f090013
			public const int linearLayout1 = 2131296275;
			
			// aapt resource value: 0x7f09001d
			public const int listView1 = 2131296285;
			
			// aapt resource value: 0x7f090009
			public const int messageEdit = 2131296265;
			
			// aapt resource value: 0x7f090008
			public const int messagesContainer = 2131296264;
			
			// aapt resource value: 0x7f090002
			public const int none = 2131296258;
			
			// aapt resource value: 0x7f090021
			public const int reset = 2131296289;
			
			// aapt resource value: 0x7f09001e
			public const int showChat = 2131296286;
			
			// aapt resource value: 0x7f09001f
			public const int showSettings = 2131296287;
			
			// aapt resource value: 0x7f090017
			public const int tableLayout = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int tableRow1 = 2131296280;
			
			// aapt resource value: 0x7f09000b
			public const int textView1 = 2131296267;
			
			// aapt resource value: 0x7f090019
			public const int textView4 = 2131296281;
			
			// aapt resource value: 0x7f090004
			public const int txtInfo = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int txtMessage = 2131296262;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int chat_activity_list_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChatLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LoginScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PatientListView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int save_time_alert_dialog = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SettingsLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int simple_patient_list_view = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Tab = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int main_layout = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int vvmenu = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040022
			public const int app_name = 2130968610;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int common_android_wear_notification_needs_update_text = 2130968580;
			
			// aapt resource value: 0x7f040011
			public const int common_android_wear_update_text = 2130968593;
			
			// aapt resource value: 0x7f04000f
			public const int common_android_wear_update_title = 2130968591;
			
			// aapt resource value: 0x7f04001f
			public const int common_google_play_services_api_unavailable_text = 2130968607;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_enable_button = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_enable_text = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_enable_title = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_error_notification_requested_by_msg = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_install_button = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_install_text_phone = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_install_text_tablet = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_title = 2130968583;
			
			// aapt resource value: 0x7f040017
			public const int common_google_play_services_invalid_account_text = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_invalid_account_title = 2130968598;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_needs_enabling_title = 2130968581;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_network_error_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_network_error_title = 2130968596;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_notification_needs_update_title = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_notification_ticker = 2130968578;
			
			// aapt resource value: 0x7f040021
			public const int common_google_play_services_sign_in_failed_text = 2130968609;
			
			// aapt resource value: 0x7f040020
			public const int common_google_play_services_sign_in_failed_title = 2130968608;
			
			// aapt resource value: 0x7f040018
			public const int common_google_play_services_unknown_issue = 2130968600;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_unsupported_text = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int common_google_play_services_unsupported_title = 2130968601;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_play_services_update_button = 2130968603;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_update_text = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_update_title = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_updating_text = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_updating_title = 2130968594;
			
			// aapt resource value: 0x7f04001e
			public const int common_open_on_phone = 2130968606;
			
			// aapt resource value: 0x7f04001c
			public const int common_signin_button_text = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int common_signin_button_text_long = 2130968605;
			
			// aapt resource value: 0x7f040023
			public const int login_title = 2130968611;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070006
			public const int ActionBar_Solid_Maintheme = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int ActionBar_Transparent_Maintheme = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int ActionBarTabStyle_Maintheme = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int ActionButton_CloseMode_Maintheme = 2131165197;
			
			// aapt resource value: 0x7f070001
			public const int AutoCompleteTextViewthememain = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int Buttonthememain = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int DropDownListView_Maintheme = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int DropDownNav_Maintheme = 2131165195;
			
			// aapt resource value: 0x7f070003
			public const int ImageButtonthememain = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int PopupMenu_Maintheme = 2131165192;
			
			// aapt resource value: 0x7f07000c
			public const int ProgressBar_Maintheme = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int ProgressBarthememain = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int RatingBarBigthememain = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int RatingBarSmallthememain = 2131165203;
			
			// aapt resource value: 0x7f070011
			public const int RatingBarthememain = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int SeekBarthememain = 2131165200;
			
			// aapt resource value: 0x7f070004
			public const int Spinnerthememain = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int SplashScreenTheme = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int Theme_Main = 2131165189;
			
			// aapt resource value: 0x7f07000e
			public const int Theme_Main_Widget = 2131165198;
			
			// aapt resource value: 0x7f070014
			public const int Togglethememain = 2131165204;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] TypefaceTextView = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public const int TypefaceTextView_customTypeface = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
